config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  resources :ingredients
  resources :recipes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients
  accepts_nested_attributes_for :ingredients, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ingredient_params
      params.require(:ingredient).permit(:recipe_id, :name, :quantity)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:name, :instructions,
                                     ingredients_attributes: [:id, :name, :quantity, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recipe_id %>
    <%= form.text_field :recipe_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Recipe</th>
      <th>Name</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.recipe_id %></td>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.quantity %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipe:</strong>
  <%= @ingredient.recipe_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @ingredient.quantity %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :instructions %>
    <%= form.text_area :instructions %>
  </div>

  <%= form.fields_for :ingredients do |ff| %>
    <%= render 'ingredient_fields', f: ff %>
  <% end %>

  <div class="actions">  
    <%= link_to_add_association 'adicionar ingrediente', form, :ingredients %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.text_field :quantity %>
  </div>

  <div class="actions">
    <%= link_to_remove_association "remover ingrediente", f %>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Instructions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.instructions %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Instructions:</strong>
  <%= @recipe.instructions %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>